### PR TITLE
Fix page listings

### PR DESCRIPTION
**Pull request by ghost**
change `.Data.Paginator.Pages` to `.Data.Pages`; I guess the API changed at some point?

### CODE REVIEW

**Comment by simonmika** [comment]
So does it support pagination?

**Comment by ghost** [comment]
It appears to, in my tests at least. It looks like they just ditched the `Paginator` dict and put its contents right in `.Data`. I'm not sure because I can only see current docs; I'm not sure what it changed *from*.

but it does appear to render pagination buttons.

**Comment by simonmika** [comment]
The pagination buttons come from line 8 `{{ partial "pagination" . }}`. Maybe there should be a way of turning of pagination when the `paginate` property of the site is set to 0 or something. But the default should be to use pagination for listings.

**Comment by ghost** [comment]
I know listings didn't work, but clearly I'm confused about how things work. I'll do some more research and fix this later.

**Comment by simonmika** [comment]
As pagination is a must for many real life sites I think it should be the default.

**Pull request closed without merging**
