### PR TITLE
make article header titles links

### PR DESCRIPTION
**Pull request by ghost**
this just wraps the `<h1>` in an `<a href="{{ .Permalink }}">` tag.

### CODE REVIEW

**Comment by simonmika** [comment]
Why? What is the purpose? Isn't it a bit odd to have the title in the header of an article clickable?

**Comment by simonmika** [comment]
For lists where not the full content is viewed a link is created. By using some somewhat hacky css one can make that link cover the title, the header or the whole representation of the article. Look at http://simonmika.com for an example. It will however need some documentation or even better a preconfigured css file.

**Comment by ghost** [comment]
I find that clickable headers are fairly common, and to me it seems more semantic to have this in markup rather than CSS. It's also nice for people who want to support crazy old browsers who don't support absolute and relative positioning. I could make this a site param though, or just leave this change in my own fork.

**Comment by simonmika** [comment]
Using site param would lead to at least the following options:

1. full article clickable
1. full article header element clickable
1. only article text clickable
1. clickable more link

As this certainly is a question of _presentation_ it belongs in the CSS and not in the content. Therefore I opt to keep the current solution but I will supplement buy supplying decently working default style sheet that can be overridden.

Anybody that for some reason still wants to modify the content may do so by overriding the appropriate partial.

**Pull request closed without merging**
